spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://madusha-user:IewGgXRnFG659pxJCO7XmJ_A9PdcSVGPkoUeFM_pRgpSo_8A@12114851-2a1e-444e-b0a6-e5f7ab183144.asia-southeast1.firestore.goog:443/database-1?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}